# Site Settings
title: Harm te Molder
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://harmtemolder.github.io"
baseurl: "/com"
images: "/com/assets/images"
permalink: ":title/"

# Author Settings
author: Harm te Molder
author-img: harm-te-molder-400.png
author-about: I work as a data engineer, focusing on marketing data. CDPs, tag managers and BigQuery hold no secrets for me.
social-github: harmtemolder
social-linkedin: harmtemolder
social-email: mail@harmtemolder.com

# Analytics Settings
google-tag-manager: GTM-P68W9HB

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude:
  - Gemfile
  - README.md
  - LICENSE
