# Site Settings
title: Harm te Molder
description: I work as a data engineer, focusing on marketing data. CDPs, tag managers and BigQuery hold no secrets for me.
url: https://harmtemolder.com
# baseurl:
images: /assets/images
styles: /assets/styles
fonts: /assets/fonts
permalink: :title/

# Author Settings
author-about: I work as an analytics engineer, focusing on marketing data. That means CDPs, tag managers and DataFrames hold no secrets from me.
author-img: harm-te-molder-200.png
author: Harm te Molder
social-email: mail@harmtemolder.com
social-github: harmtemolder
social-linkedin: harmtemolder
social-phone: "+31493219013"
social-signal: "+31642696616"

# Analytics Settings
google-tag-manager: GTM-P68W9HB

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-compress-images
paginate: 5
paginate_path: /page/:num
exclude:
  - Gemfile
  - README.md
  - LICENSE
  - _compress_images_cache.yml
  - serve.sh
sass:
  style: compressed
compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"
imageoptim:
  verbose: false
  svgo: false
